### ISSUE TITLE
Memory Leak Somewhere?

### ISSUE THREAD

**Issue by CruelAlpha** [TigoDevelopment/TigoAntiCheat#11]
Hello Tigo,
I was wondering if this was something that was reported by anyone else prior.
The anti-cheat (at random times) seem to gain alot of ram (upto 140mb usage)
Screenshot: 
![image](https://user-images.githubusercontent.com/29218750/74083456-5cd32200-4ab8-11ea-96e4-2fd77910019a.png)
This usually happens during high load (32+ people), however, i can't seem to replicate it all the time, possibly happens after it bans a couple of people aswell.

Thanks!

**Comment by ThymonA** [comment]
This problem has never been reported before and I don't have this on my server, average players: 50-60 per day. What you can do is run `profiler` and forward that file. That will explain more about this issue, I'll see if I can find the problem or if I can simulate this leak.

**Comment by ThymonA** [comment]
I have investigated this problem and come to the following conclusion: There was a leak in memory useage, this problem is possible after someone is banned en the command to get the number of available commands is executed. Relogging solved this problem. I have already released an update and possibly solved the problem.
