### ISSUE TITLE
Banned By No Reason :/

### ISSUE THREAD

**Issue by HeyYuvraj** [TigoDevelopment/TigoAntiCheat#28]
Hey,
Me and other 3 people were banned for Lua Executor found and 1 for GodMod but not a single person was using any kind of godmod and lua executor.
I have changed my all trigger events properly and re-checked all of them. 
Please Help

**Comment by Richards0nd** [comment]
It's probably some kind of script that is bringing players to life, check all your scripts and see if there are any scripts that are bringing players to life ...
Priority to esx_ambulancejob

**Comment by ThymonA** [comment]
Can I get the ban reasons, do not need the identifiers (only the ban reason it self)

**Comment by HeyYuvraj** [comment]
Reason: Lua executor found on player

> Can I get the ban reasons, do not need the identifiers (only the ban reason it self)

**Comment by ThymonA** [comment]
This is because the player tells the server for a second time that they are loaded TigoAntiCheat.
This may be due to someone restarting their resource using `restart TigoAntiCheat` or an external tool.
A player would never be able to invoke this function a second time without using a `restart command` or `external tools`.

**Comment by HeyYuvraj** [comment]
> This is because the player tells the server for a second time that they are loaded TigoAntiCheat.
> This may be due to someone restarting their resource using `restart TigoAntiCheat` or an external tool.
> A player would never be able to invoke this function a second time without using a `restart command` or `external tools`.

Alright!
