### ISSUE TITLE
Not a isue but a cheat

### ISSUE THREAD

**Issue by NotKrma** [TigoDevelopment/TigoAntiCheat#32]
Hello, I have a dll injector that can execute a menu, this menu can give weapons, make itself invisible, among other things. I don't know why the anticheat is not stopping it. I have no admin or anything.

**Comment by ThymonA** [comment]
Injecting files is always possible, FiveM is the only one that can build protection for it or detect when someone is injecting something. With the recent update of es_extended, it is not possible to cheat weapons in (You have them in your hand, but not in your inventory, which makes it impossible to pass them to other players), so it is up to everyone to make sure their scripts stay up to date. The fact that you are invisible may be true, because TigoAntiCheat does not check for that type of cheat at the moment. Cheating is and always will be possible, with or without AntiCheat. The only difference is that TigoAntiCheat helps detect hackers.
