### ISSUE TITLE
Network event overflow

### ISSUE THREAD

**Issue by h03ein72** [TigoDevelopment/TigoAntiCheat#34]
Hello,
After joining to server, you will dropped and an error appear "You are disconnected by server: Reliable network event overflow" and Script error @mustache/mustache.lua:495: Unclosed tag at 48.

![11](https://user-images.githubusercontent.com/9111099/80146601-576d7a00-85c7-11ea-84c3-f1057bc26c44.png)

Also I have an another question about changing esx_ folders names, Is needed to change them?

Thanks.

**Comment by ThymonA** [comment]
I have now installed this version on multiple servers and experienced zero problems by my own.
What it looks like at the moment is an error in the translations, what language do you use in TigoAntiCheat?
I might also be another problem, I need your name what your using when joining the server. Could you sent me the name behind Connecting... when your connecting to the server?
On your last question, that's not necessary, as long as all events are renamed.

**Comment by h03ein72** [comment]
Hello again and thank you for your answer. about translation... I actually used both nl and en on TigoAntiCheat. I also started the tigo and mustache at the top of everything else [even essentialmode and es_extended]. My steam joining name is h03ein72 and in-game name is Hossein_Vsh. 
Thanks again.

**Comment by ThymonA** [comment]
I gonna check where this problem might be, thanks for the information.

**Comment by h03ein72** [comment]
Another thing that could be useful is the mustache parsing nl language translation in TigoAntiCheat perfectly fine but after you dropped with en language you will have that error [picture] on your server console.

**Comment by ThymonA** [comment]
It is possible that the problem has now been solved by the latest commit (https://github.com/TigoDevelopment/TigoAntiCheat/commit/42a5c274f3c9d204f6150e160fe5f63f912d2479). Number of tags were incorrectly closed in english translation

**Comment by h03ein72** [comment]
I just fix the problem. It wasn't the anticheat problem. I double check the events and found some esx events like this that caused dropping players from the server: 

TriggerEvent(
                "esx:

Thank you for your answers.

**Comment by ThymonA** [comment]
That's because all standard esx events are blacklisted. It is necessary to rename all esx events. If you think of disabling ban on default esx events (not recommended), you should do the following:

Remove `'server/fake_events.lua',` in `fxmanifest.lua`
https://github.com/TigoDevelopment/TigoAntiCheat/blob/master/fxmanifest.lua#L21

Disable `fake_events` in `AntiCheat.Generators` in`config.lua`
https://github.com/TigoDevelopment/TigoAntiCheat/blob/master/config.lua#L25
Change `enabled = true` to `enabled = false`

Best advice is just to rename all esx events to make it easier to detect cheaters.
